import { CircleHelp, MapPin, ScanLine } from 'lucide-react';
import type { TrafficResult, IntersectionCandidate } from '../types';
import CandidateIntersections from './CandidateIntersections';
import ProvenancePanel from './ProvenancePanel';
interface Props { result?: TrafficResult; intersection?: IntersectionCandidate | null; candidates?: IntersectionCandidate[]; onCandidateSelect?: (candidate: IntersectionCandidate) => void; loading?: boolean; error?: string | null; hasLocation?: boolean; }
export default function ResultCard({ result, intersection, candidates = [], onCandidateSelect, loading, error, hasLocation }: Props) {
  if (result) return <div className="result-card"><div className="result-heading"><span className="eyebrow">RECORD DETAILS</span><span className={'result-badge ' + (result.result_type === 'UNAVAILABLE' ? 'unavailable' : '')}>{result.result_type.split('_').join(' ').toLowerCase()}</span></div>{result.result_type === 'UNAVAILABLE' ? <p className="no-data"><CircleHelp size={18} />{result.message || 'No authoritative data available for this request.'}</p> : <><div className="measurement"><strong>{result.value?.toLocaleString() ?? '—'}</strong><span>{result.unit}</span></div>{result.message && <p className="result-description">{result.message}</p>}</>}{result.provenance && <ProvenancePanel provenance={result.provenance} />}</div>;
  return <>{intersection ? <div className="selected-location"><div className="location-icon"><MapPin size={19} /></div><div><span className="eyebrow">SELECTED INTERSECTION</span><h3>{intersection.name}</h3><p>{intersection.latitude.toFixed(5)}, {intersection.longitude.toFixed(5)}</p></div></div> : !candidates.length && <div className="location-empty"><ScanLine size={22} /><div><strong>{loading ? 'Finding nearby intersections' : hasLocation ? 'No intersections found' : 'Your next insight starts here'}</strong><p>{loading ? 'Looking up official location records…' : hasLocation ? 'Try another point or a more specific address.' : 'Click the map or search for a place to begin.'}</p></div></div>}{error && <p className="selection-error" role="alert">{error}</p>}{candidates.length > 0 && onCandidateSelect && <details className="candidate-details" open={intersection ? undefined : true}><summary>{intersection ? 'Change intersection' : 'Choose an intersection'}<span>{candidates.length} nearby</span></summary><CandidateIntersections candidates={candidates} onSelect={onCandidateSelect} selectedId={intersection?.id} /></details>}</>;
}

